Repository SELab-2/OSOC-1, pull requests merged in 2022-05, with the labels that each got.

#280 Fix cascade on Project positions and Student class skills
  backend/src/main/kotlin/be/osoc/team1/backend/entities/Project.kt
  backend/src/main/kotlin/be/osoc/team1/backend/entities/Student.kt
  backend/src/main/kotlin/be/osoc/team1/backend/services/ServicesUtil.kt
  backend/src/test/kotlin/be/osoc/team1/backend/integrationtests/EntitySaveTests.kt
Labels: bug

#290 Editions uiux
  frontend/components/editions/EditionDeletionPopup.tsx
  frontend/pages/editions.tsx
Labels: UI/UX

#304 Optimize filterByNotYetAssigned
  backend/src/main/kotlin/be/osoc/team1/backend/entities/Student.kt
  backend/src/test/kotlin/be/osoc/team1/backend/unittests/StudentControllerTests.kt
Labels: enhancement

#308 Refresh bug with multiple requests
  frontend/hooks/useAxiosAuth.ts
Labels: bug

#299 Add basic frontend polling
  frontend/components/StudentSidebar.tsx
  frontend/components/projects/ProjectTile.tsx
  frontend/components/student/StudentHolder.tsx
  frontend/components/student/StudentView.tsx
  frontend/components/students/StudentTile.tsx
  frontend/package.json
  frontend/pages/[editionName]/projects.tsx
  frontend/pages/[editionName]/students.tsx
  frontend/yarn.lock
Labels: enhancement

#318 update frontend dependencies
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#314 style: fix header styling
  frontend/components/Header.tsx
Labels: UI/UX

#325 fix polling projects bug
  frontend/components/projects/ProjectTile.tsx
  frontend/hooks/useOnScreen.ts
  frontend/pages/[editionName]/projects.tsx
Labels: bug

#301 Fix aborted requests causing an IllegalStateException
  backend/src/main/kotlin/be/osoc/team1/backend/security/AuthorizationFilter.kt
Labels: bug

#330 Fix positions on new projects and status suggestions having a blank edition field
  backend/src/main/kotlin/be/osoc/team1/backend/controllers/ProjectController.kt
  backend/src/main/kotlin/be/osoc/team1/backend/controllers/StudentController.kt
  backend/src/main/kotlin/be/osoc/team1/backend/entities/Project.kt
Labels: bug

#333 remove dialect from properties
  backend/src/main/resources/application.properties
Labels: bug

#313 Data persistence
  frontend/components/Header.tsx
  frontend/components/PersistLogin.tsx
  frontend/context/AuthProvider.tsx
  frontend/hooks/useRefreshToken.ts
  frontend/pages/[editionName]/projects.tsx
  frontend/pages/[editionName]/students.tsx
  frontend/pages/editions.tsx
  frontend/pages/index.tsx
  frontend/pages/login.tsx
  frontend/pages/users.tsx
Labels: enhancement

#347 refactor: add informative title to pages
  frontend/pages/[editionName]/projects.tsx
  frontend/pages/[editionName]/students.tsx
  frontend/pages/_app.tsx
  frontend/pages/editions.tsx
  frontend/pages/login.tsx
  frontend/pages/register.tsx
  frontend/pages/users.tsx
  frontend/pages/wait.tsx
Labels: UI/UX

#364 update dependencies for dependabot
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#371 chore: remove index page
  frontend/pages/index.tsx
Labels: refactor

#362 Communication delete endpoint
  backend/src/main/kotlin/be/osoc/team1/backend/controllers/CommunicationController.kt
  backend/src/main/kotlin/be/osoc/team1/backend/controllers/StudentController.kt
  backend/src/main/kotlin/be/osoc/team1/backend/entities/Communication.kt
  backend/src/main/kotlin/be/osoc/team1/backend/exceptions/InvalidCommunicationIdException.kt
  backend/src/main/kotlin/be/osoc/team1/backend/repositories/CommunicationRepository.kt
  backend/src/main/kotlin/be/osoc/team1/backend/services/BaseService.kt
  backend/src/main/kotlin/be/osoc/team1/backend/services/CommunicationService.kt
  backend/src/main/kotlin/be/osoc/team1/backend/services/StudentService.kt
  backend/src/test/kotlin/be/osoc/team1/backend/integrationtests/PostgresConnectionTests.kt
  backend/src/test/kotlin/be/osoc/team1/backend/unittests/CommunicationControllerTests.kt
  backend/src/test/kotlin/be/osoc/team1/backend/unittests/CommunicationServiceTests.kt
  backend/src/test/kotlin/be/osoc/team1/backend/unittests/SerializationTests.kt
  backend/src/test/kotlin/be/osoc/team1/backend/unittests/StudentServiceTests.kt
  docs/osoc.yaml
Labels: enhancement

#372 feat: reroute on index page
  frontend/pages/index.tsx
  frontend/pages/login.tsx
Labels: enhancement

#363 Frontend student page functionality
  docs/osoc.yaml
  frontend/components/student/StudentHolder.tsx
  frontend/components/student/StudentView.tsx
  frontend/lib/endpoints.ts
  frontend/pages/[editionName]/students.tsx
  frontend/styles/line.css
Labels: UI/UX

#350 Delete users prompt
  frontend/components/users/UserDeleteForm.tsx
  frontend/components/users/UserTable.tsx
  frontend/components/users/UsertableRow.tsx
  frontend/pages/users.tsx
  frontend/public/favicon.ico
Labels: enhancement

#344 Communications page
  frontend/components/Header.tsx
  frontend/components/StudentSidebar.tsx
  frontend/components/communications/CommsCreationPopup.tsx
  frontend/components/communications/CommsDeletePopup.tsx
  frontend/components/communications/CommsTable.tsx
  frontend/components/communications/CommsTableRow.tsx
  frontend/components/projects/ProjectPopup.tsx
  frontend/components/projects/ProjectTile.tsx
  frontend/components/student/StudentView.tsx
  frontend/lib/endpoints.ts
  frontend/lib/requestUtils.ts
  frontend/lib/types.ts
  frontend/package.json
  frontend/pages/[editionName]/communications.tsx
  frontend/pages/[editionName]/projects.tsx
  frontend/yarn.lock
Labels: enhancement

#365 Fix Searchbars & dropdowns
  frontend/components/StudentSidebar.tsx
  frontend/components/projects/ProjectConflict.tsx
  frontend/components/projects/ProjectPopup.tsx
  frontend/components/projects/ProjectTile.tsx
  frontend/lib/requestUtils.ts
  frontend/pages/[editionName]/projects.tsx
  frontend/pages/users.tsx
Labels: UI/UX

#383 Infinite list fix
  frontend/components/InfiniteList.tsx
  frontend/components/StudentSidebar.tsx
  frontend/components/projects/ProjectPopup.tsx
  frontend/hooks/useOnScreen.ts
Labels: bug

#398 Fix rerouting on index page
  frontend/pages/index.tsx
Labels: bug

#387 Only assigned filter
  backend/src/main/kotlin/be/osoc/team1/backend/controllers/StudentController.kt
  backend/src/main/kotlin/be/osoc/team1/backend/entities/Student.kt
  backend/src/test/kotlin/be/osoc/team1/backend/unittests/StudentControllerTests.kt
  docs/osoc.yaml
  frontend/components/StudentSidebar.tsx
Labels: enhancement

#399 Use injected environment and emailsender to improve testing
  backend/src/main/kotlin/be/osoc/team1/backend/services/EmailService.kt
  backend/src/test/kotlin/be/osoc/team1/backend/unittests/ForgotPasswordServiceTests.kt
Labels: enhancement

#381 Cascade deletion bugs
  backend/src/main/kotlin/be/osoc/team1/backend/entities/Project.kt
  backend/src/main/kotlin/be/osoc/team1/backend/entities/Student.kt
  backend/src/main/kotlin/be/osoc/team1/backend/entities/User.kt
Labels: bug

#380 Fix reloading issues
  frontend/components/StudentSidebar.tsx
  frontend/hooks/useAxiosAuth.ts
  frontend/lib/requestUtils.ts
  frontend/package.json
  frontend/pages/[editionName]/communications.tsx
  frontend/pages/[editionName]/projects.tsx
  frontend/pages/[editionName]/students.tsx
  frontend/pages/editions.tsx
  frontend/pages/users.tsx
  frontend/yarn.lock
Labels: bug

#409 Improve communications page
  backend/pom.xml
  backend/src/main/kotlin/be/osoc/team1/backend/entities/Communication.kt
  backend/src/main/resources/application.properties
  backend/src/test/resources/application.properties
  docs/osoc.yaml
  frontend/components/communications/CommsCreationPopup.tsx
  frontend/components/communications/CommsTable.tsx
  frontend/components/communications/CommsTableRow.tsx
  frontend/lib/types.ts
  frontend/pages/[editionName]/communications.tsx
Labels: enhancement

#411 Adjust the styling of status suggest/set
  frontend/components/student/StudentView.tsx
Labels: enhancement

#382 Add logout functionality
  backend/src/main/kotlin/be/osoc/team1/backend/security/SecurityConfig.kt
  backend/src/main/kotlin/be/osoc/team1/backend/security/TokenLogoutHandler.kt
  backend/src/test/kotlin/be/osoc/team1/backend/integrationtests/AuthorizationTests.kt
  docs/osoc.yaml
  frontend/components/Header.tsx
  frontend/components/Info.tsx
  frontend/components/PersistLogin.tsx
  frontend/lib/endpoints.ts
  frontend/pages/[editionName]/communications.tsx
  frontend/pages/[editionName]/projects.tsx
  frontend/pages/[editionName]/students.tsx
  frontend/pages/editions.tsx
  frontend/pages/login.tsx
  frontend/pages/users.tsx
Labels: enhancement

#415 feat: add closeable errors
  frontend/components/Error.tsx
  frontend/components/projects/ProjectConflict.tsx
  frontend/components/projects/ProjectTile.tsx
  frontend/pages/[editionName]/communications.tsx
  frontend/pages/[editionName]/projects.tsx
  frontend/pages/[editionName]/students.tsx
  frontend/pages/editions.tsx
  frontend/pages/users.tsx
Labels: enhancement

#416 style: update color contrasts
  frontend/components/StudentSidebar.tsx
  frontend/components/editions/EditionCard.tsx
  frontend/components/editions/EditionCreateForm.tsx
  frontend/components/student/StudentView.tsx
  frontend/pages/[editionName]/communications.tsx
  frontend/pages/[editionName]/projects.tsx
Labels: UI/UX

#423 remove unused Recoil dependency
  docs/architecture_choices.md
  frontend/atoms/index.ts
  frontend/atoms/registerAtoms.ts
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/yarn.lock
Labels: dependencies

#425 UI/UX updates on users and comms pages
  frontend/components/communications/CommsTable.tsx
  frontend/components/users/UserTable.tsx
  frontend/pages/[editionName]/communications.tsx
Labels: UI/UX

#418 Make header fixed
  frontend/components/Header.tsx
  frontend/components/StudentSidebar.tsx
  frontend/components/communications/CommsTable.tsx
  frontend/components/student/StudentView.tsx
  frontend/components/users/UserTable.tsx
  frontend/pages/[editionName]/communications.tsx
  frontend/pages/[editionName]/projects.tsx
  frontend/pages/[editionName]/students.tsx
  frontend/pages/editions.tsx
  frontend/pages/users.tsx
  frontend/styles/line.css
Labels: UI/UX

#424 style: remove button to add an image as this isn't supported
  frontend/components/editions/EditionCreateForm.tsx
Labels: refactor, UI/UX

#420 Studentsidebar fixes
  frontend/components/StudentSidebar.tsx
  frontend/components/projects/ProjectTile.tsx
  frontend/components/students/StudentTile.tsx
  frontend/lib/conversionUtils.ts
  frontend/lib/types.ts
  frontend/pages/[editionName]/projects.tsx
  frontend/pages/[editionName]/students.tsx
  frontend/styles/line.css
Labels: UI/UX

#427 feat: make position text background connect
  frontend/components/projects/ProjectTile.tsx
  frontend/styles/line.css
Labels: UI/UX

#419 Improve backend test coverage
  backend/src/test/kotlin/be/osoc/team1/backend/unittests/UrlDeserializerTests.kt
Labels: enhancement

#429 feat: allow to make different edition
  docker/populate
  docker/subpopulate.py
Labels: enhancement

#428 Project fixes
  frontend/components/projects/ProjectTile.tsx
  frontend/pages/[editionName]/projects.tsx
Labels: bug

#430 chore: fix loading icon on project tile
  frontend/components/projects/ProjectTile.tsx
Labels: bug

#436 add extra check before rendering
  frontend/components/projects/ProjectTile.tsx
Labels: bug
